apiVersion: v1
kind: Secret
metadata:
  name: notification-db-secrets
  namespace: vroom-dev
type: Opaque
stringData:
  database_url: postgres://notification_svc:vroom_notification_pass@postgres.platform.svc.cluster.local:5432/vroom?sslmode=disable
  password: vroom_notification_pass
