apiVersion: v1
kind: Secret
metadata:
  name: ride-db-secrets
  namespace: vroom-dev
type: Opaque
stringData:
  database_url: postgres://ride_svc:vroom_ride_pass@postgres.platform.svc.cluster.local:5432/vroom
  password: vroom_ride_pass
