apiVersion: v1
kind: Secret
metadata:
  name: user-db-secrets
  namespace: vroom-dev
type: Opaque
stringData:
  database_url: postgres://user_svc:vroom_user_pass@postgres.platform.svc.cluster.local:5432/vroom?sslmode=disable
  password: vroom_user_pass
